### ISSUE TITLE
Startup issue: spring cache instance cannot be null

### ISSUE THREAD

**Issue by mraible** [mraible/jhipster-stormpath-example#2]
Fixed by turning off cacheManager in `application.yml`:

``` yaml
stormpath:
    client:
        cacheManager:
            enabled: false
```

Level of concern: high, not sure why our caching doesn’t work with JHipster’s config by default. When I created my project, I chose to use EhCache for Hibernate’s 2nd level cache.
