### ISSUE TITLE
Fix CSS on login form

### ISSUE THREAD

**Issue by mraible** [mraible/jhipster-stormpath-example#8]
![login-form](https://cloud.githubusercontent.com/assets/17892/19208855/d4970042-8cb4-11e6-8eda-30e5091349ce.png)

**Comment by mraible** [comment]
Adding `class="form-login"` to the outer div and the following CSS seems to do the trick.

``` css
@media (min-width: 768px) {
    .form-login {
        padding: 5px 15px 0;
    }

    .form-login .col-sm-offset-4 {
        margin-left: 0;
    }

    .form-login .col-sm-4 {
        float: none;
        width: 100%;
    }

    .form-login .form-horizontal .control-label {
        padding-top: 0;
        padding-bottom: 5px;
        text-align: left;
    }
}
```

<img width="674" alt="login-css" src="https://cloud.githubusercontent.com/assets/17892/19209192/25e3f0f4-8cba-11e6-8782-58bcd8a982fd.png">
